Contract_Assistant/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', loginuser.verifyuser, name='signin'),
    path('signout/', logoutuser.finishconnection, name='sinout'),
    # path('register/', appuser.pricing, name='register'),
    path('register/', appuser.register2, name='register'),
    path('pricing/', appuser.pricing, name='princing'),
    path('RuleManager/', include('RuleManager.urls')),
    path('rulemanager/', include('RuleManager.urls')),
    path('ruleManager/', include('RuleManager.urls')),
    path('Rulemanager/', include('RuleManager.urls')),
    path('ServiceUser/', include('ServiceUser.urls')),
    # path('create-rule/', include('RuleManager.urls')),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('Expertsystem/', include('ExpertSystem.urls')),
    path('', include('ExpertSystem.urls')),
    path('plans/', include('plans.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/newpassword_reset_form.html',
        email_template_name = 'registration/newpassword_reset_email.html',
        subject_template_name= 'registration/newpassword_reset_subject.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/newpassword_reset_done.html')
         , name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/newpassword_reset_confirm.html')
         , name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/newpassword_reset_completed.html')
         , name='password_reset_complete'),
]

ExpertSystem/urls.py
from django.urls import  path
from . import forms, views
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ExpertSystem'
urlpatterns = [
    path('contractdemo', forms.initengine, name='expert_initial'),
    path('classiccontractdemo', forms.initengine_classic, name='expert_initial_classic'),
    path('update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    # path('', views.luncher, name = 'luncher'),
    # path('', login_required(PricingView.as_view(template_name='ExpertSystem/home.html')), name = 'luncher'),
    path('', PricingView.as_view(template_name='ExpertSystem/home.html'), name = 'luncher'),
    path("expert_contract/", forms.Creat_Expert, name='expert_contract'),
    path('ContractExpert/', forms.Creat_Expert, name='expert_contract'),
    path('expert_contract_byajax/', views.expert_contract_byajax, name='expert_contract_byajax'),
    path('rewindengine/', views.rewindengine, name='rewindengine'),
    path('update_facts/', views.update_facts, name='update_facts'),

    path('about/', views.about, name='about'),
    path('contact/', forms.contact, name='contact'),
    # path('RuleManager/', include('RuleManager.urls')),
]

RuleManager/urls.py
from django.urls import path, include
from . import forms, views
from django.views.generic.edit import CreateView
from RuleManager.models import Rules
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

app_name = 'RuleManager'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('update_rule_list/', views.filterrules, name='update_rule_list'),
    path('update_fact_list/', views.filterfacts, name='update_fact_list'),
    path('loginuser/', loginuser.verifyuser, name='loginuser'),
    path('register/', appuser.register, name='register'),
    path('logoutuser/', logoutuser.finishconnection, name='logoutuser'),
    # path('create_supervisor/', supervisor.create_supervisor, name='create_supervisor'),
    # path('create_developer/', developer.create_developer, name='create_developer'),
    path('<int:rule_id>/', views.detail, name='detail'),
    path('create_condition/', forms.create_condition, name='create_condition'),
    path('facts/create_fact/', forms.create_fact_by_model, name='create_fact'),
    path('update_facts/', views.update_facts, name='update_facts'),
    path('update_domains/', views.update_domains, name='update_domains'),
    path('create_rule_by_model/', forms.create_rule_by_model, name='create_rule_by_model'),
    path ('create_rule_cbv/', CreateView.as_view(model=Rules, fields= ['condition','consequence','pub_date','rule_type'],
        template_name="RuleManager/create_rule_by_model.html", success_url ='index'), name="create_rule_cbv"),
    path('edit_rule/<int:rule_id>/', forms.edit_rule_by_index, name='edit_rule'),
    path('delete_rule/<int:rul_ind>/', views.delete_rule_by_index, name='delete_rule'),
    path('facts/', views.factlist, name='factlist'),
    path('facts/<int:fact_ind>/', views.factdetail, name='factdetail'),
    path('facts/edit_fact/<int:fact_ind>/', forms.edit_fact_by_index, name='edit_fact'),
    path('facts/delete_fact/<int:fact_ind>/', views.delete_fact_by_index, name='delete_fact'),
    path('domains/', views.domainlist, name='domainlist'),
    path('domains/<int:dom_ind>/', views.domaindetail, name='domaindetail'),
    path('domains/create_domain/', forms.create_domain_by_model, name='create_domain'),
    path('domains/edit_domain/<int:dom_ind>/', forms.edit_domain_by_index, name='edit_domain'),
    path('domains/delete_domain/<int:dom_ind>/', views.delete_domain_by_index, name='delete_domain'),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('ExpertSystem/', include('ExpertSystem.urls')),
    path('loginuser/expertsystem/', include('ExpertSystem.urls')),
     path('loginuser/Expertsystem/', include('ExpertSystem.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_form.html')
    #      , name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_done.html')
    #      , name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_confirm.html')
    #      , name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_complete.html')
    #      , name='password_reset_complete'),

]

ServiceUser/urls.py
from django.urls import path, include
from . import forms, views
from .UserManagement import loginuser, appuser
from RuleManager import views as Rule_views
from RuleManager import forms as Rule_forms
from .messagemanager import restore_default_messages
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ServiceUser'
urlpatterns = [
    # *** auth user urls ***
    path('create_user/', forms.create_user, name='create_user'),
    path('create_user/result', views.create_user_result, name='create_user-result'),
    path('edit_user/', appuser.edit_user, name='edit_user'),
    # *** auth user urls ***

    # *** supervisor urls ***
    path('supervisors/', views.supervisorlist, name='supervisorlist'),
    path('supervisors/create/', forms.create_supervisor, name='create_supervisor'),
    path('supervisors/<int:sup_id>/', views.supervisor_detail, name='supervisordetail'),
    path('supervisors/edit/<int:sup_id>/', forms.edit_supervisor_by_index, name='edit_supervisor'),
    path('supervisors/delete/<int:sup_id>/', views.delete_supervisor_by_index, name='delete_supervisor'),
    # *** supervisor urls ***

    # *** developer urls ***
    path('developers/', views.developerlist, name='developerlist'),
    path('developers/create/', forms.create_developer, name='create_developer'),
    path('developers/<int:dev_id>/', views.developer_detail, name='developerdetail'),
    path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** developer urls ***

    # *** appuser urls ***
    path('plans/', include('plans.urls')),
    # path('', views.dashboard2, name='user_dashboard'),
    path('', views.dashboard, name='user_dashboard2'),
    path('noaccess/', views.permission, name='Forbidden_content'),
    path('registration/<mode>/', appuser.register, name='registration'),
    # path('registration/', appuser.register2, name='registration'),
    path('registration/activate/<uidb64>/<token>/', appuser.activate, name='activate'),
    # path('account/', views.account, name='user_account'),
    path('account/',login_required(PricingView.as_view(template_name='ServiceUser/useraccount2.html')) , name='user_account2'),
    path('account/upgrade/', forms.upgradeaccount, name='upgrade_user_account'),
    path('account/limitations/', views.accountlimit, name='accountlimit'),
    path('payments/', views.paymentlist, name='user_payments'),
    path('staffs/', views.userstaffs, name='user_staffs'),
    path('staffs/add/', forms.create_employee, name='create_userstaff'),
    path('staffs/<int:staff_id>/edit/',forms.edit_employee_by_index, name='edit_userstaff'),
    path('staffs/<int:staff_id>/delete/', views.delete_employee_by_index, name='delete_userstaff'),
    path('staffs/<int:staff_id>/detail/', views.staffdetail, name='user_staffdetail'),
    path('experts/', views.userexperts, name='user_expertmodel'),
    path('experts/config', forms.configengine, name='engineconfig'),
    path('experts/config/restore', restore_default_messages, name='restoredefaults'),
    path('experts/add/', forms.create_expertmodel, name='create_expertmodel'),
    path('experts/<int:exp_id>/', views.userexpertdetail, name='user_expertdetail'),
    path('experts/<int:exp_id>/controlpanel/', views.controlpanel, name='controlpanel'),
    path('experts/<int:exp_id>/update_facts/', views.update_domain_facts, name='update_facts'),
    path('experts/<int:exp_id>/edit/', forms.userexpertedit, name='user_expert_edit'),
    path('experts/<int:exp_id>/delete/', views.userexpertdelete, name='user_expert_delete'),
    path('experts/<int:exp_id>/start/', forms.userexpertstart, name='user_expert_start'),
    path('experts/<int:exp_id>/start/update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    path('experts/<int:exp_id>/startclassic/', forms.userexpertstartclassic, name='user_expert_start_classic'),
    path('experts/<int:exp_id>/startclassic/update_detailfacts/', forms.update_detailfacts, name='update_classic_detailfacts'),
    path('experts/<int:exp_id>/RuleManager/', Rule_views.index, name='user_expertrules'),
    path('experts/<int:exp_id>/RuleManager/create_condition', Rule_forms.create_condition,
         name='user_expert_createcondition'),
    path('experts/<int:exp_id>/RuleManager/controlpanel', Rule_views.controlpanel,
         name='user_expert_controlpanel'),
    path('experts/<int:exp_id>/RuleManager/add/',Rule_forms.create_rule_by_model ,
         name='user_expertnewrule'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/',Rule_views.detail ,
         name='user_expertrule_detail'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/edit/',Rule_forms.edit_rule_by_index,
         name='user_expertrule_edit'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/delete/',Rule_views.delete_rule_by_index,
         name='user_expertrule_delete'),
    path('experts/<int:exp_id>/RuleManager/facts',Rule_views.factlist , name='user_expertfacts'),
    path('experts/<int:exp_id>/RuleManager/facts/add',Rule_forms.create_fact_by_model ,
         name='user_expertnewfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload',Rule_forms.upload_fact_file ,
         name='user_expert_uploadfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload/result',Rule_views.upload_fact_result ,
         name='factupload_result'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/',Rule_views.factdetail ,
         name='user_expertfact_detail'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/edit/',Rule_forms.edit_fact_by_index ,
         name='user_expertfact_edit'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/delete/',Rule_views.delete_fact_by_index ,
         name='user_expertfact_delete'),
    path('experts/<int:exp_id>/RuleManager/domains', Rule_views.domainlist, name='user_expertdomains'),
    path('<username>/experts/<int:exp_id>/RuleManager/domains/add', Rule_forms.create_domain_by_model,
         name='user_expertnewdomain'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/', Rule_views.domaindetail,
         name='user_expertdomain_detail'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/edit/', Rule_forms.edit_domain_by_index,
         name='user_expertdomain_edit'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/delete/', Rule_views.delete_domain_by_index,
         name='user_expertdomain_delete'),
    path('experts/<int:exp_id>/RuleManager/domains/add',Rule_forms.create_domain_by_model ,
         name='user_expertnewdomain'),

    # path('<username>/experts/create', views.developer_detail, name='developerdetail'),
    # path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    # path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** appuser urls ***

]

zarinpal/urls.py
# Github.com/Rasooll
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('', views.verify , name='verify'),
]

ExpertSystem/models.py
from django.db import models
from ServiceUser.models import App_User, Employee
# from RuleManager.models import Rules, Facts
# Create your models here.
class Comments(models.Model):

    name = models.CharField( max_length=255, blank=False )
    email=models.EmailField(max_length=255, blank=False )
    subject = models.TextField(max_length=3000, blank=False )

    def __str__(self):
        return (self.subject[:100] + '...') if len(self.subject) > 100 else self.subject

class Expertmodel(models.Model):
    _PUB = 'PUBLIC'
    _USER = 'RESTRICTED'
    _ACCESS = [(_PUB, 'دسترسی عمومی'),(_USER, 'دسترسی فقط برای کاربران')]
    name = models.CharField(max_length=200, verbose_name='نام سیستم خبره')
    appuser = models.ForeignKey('ServiceUser.App_User', on_delete=models.DO_NOTHING, related_name='user', verbose_name='مالک سیستم خبره')
    accesstype = models.CharField(choices=_ACCESS, default=_PUB,max_length=10,  verbose_name='نحوه دسترسی به سیستم خبره')
    # authorizedusers = models.ManyToManyField(Employee,related_name='allowedusers_fiels',
    #                                          limit_choices_to=Employee.objects.filter(manager=appuser))



    def get_related_facts(self):
        fact_set =self.factowner_field.all()
        if fact_set.count():
            return fact_set
        else:
            return None

    def get_related_rules(self):
        rule_set =self.ruleowner_field.all()
        if rule_set.count():
            return rule_set
        else:
            return None

    def get_related_domains(self):
        domain_set = self.domainowner_field.all()
        if domain_set.count():
            return domain_set
        else:
            return None

    def __str__(self):
        return self.name

    def getowneruser(self):
        return self.appuser.user_auth.username

ServiceUser/templates/ServiceUser/UserManagement/create_appuser.html
{% extends "managementbase.html" %}
{% block title_html %}
ایجاد حساب کاربری
{% endblock %}
{% block h1 %}
<!--<div class="container">-->
ایجاد حساب کاربری
{% endblock %}
{% block article_content %}

<div class="signup-bg-img">
<form method="post" action="{% url "ServiceUser:registration" registmode %}" class="signin-container">
{% csrf_token %}
<div class="infomsg">
    <div class="infoheader">اطلاع</div>
    <p>
        برای استفاده از سامانه هوشمند حساب کاربری خود را ایجاد نمایید
    </p>
</div>
<div class="notemsg">
    <div class="noteheader">نکته</div>
    <p>
      ورود اطلاعاتی که با رنگ قرمز مشخص شده اند اجباری می باشد</p>
</div>
<hr>
    <ul class="errorlist" >
        {% for errfield,errmsg in form.errors.items %}
           {{ errfield }}:{{ errmsg }}
        {% endfor %}
    </ul>
<tr>
    <th><label for="id_fname" >نام:</label></th>
{#   <td> <input  type="text" placeholder="نام خود را وارد کنید" name="fname" maxlength="30" id="id_fname" >#}
{#    </td>#}
    {{ form.fname }}
</tr>
<tr>
    <th><label for="id_lname" >نام خانوادگی:</label></th>
{#   <td> <input  type="text" placeholder="نام خانوادگی خود را وارد کنید" name="lname" maxlength="150" id="id_lname">#}
{#    </td>#}
{{ form.lname }}
</tr>

<tr>
    <th><label for="id_login" class="star">نام کاربری:</label> </th>
{#    <td><input  type="text" placeholder="نام کاربری را وارد کنید" name="login" maxlength="150" required id="id_login">#}
{#    </td>#}
{{ form.login }}
</tr>
<tr>
    <th><label for="id_email" class="star">رایانامه :</label> </th>
{#    <td><input  type="text" placeholder="رایانامه خود را وارد کنید" name="email" maxlength="150" required id="id_email">#}
{#    </td>#}
{{ form.email }}
</tr>
<tr>
    <th><label for="id_password" class="star">گذرواژه:</label> </th>
{#    <td><input  type="password" placeholder="گذرواژه را وارد کنید" name="password" required id="id_password">#}
{#    </td>#}
{{ form.password }}
</tr>
<tr>
    <th><label for="id_password_bis" class="star">تکرار گذرواژه :</label> </th>
{#    <td><input  type="password" placeholder="گذرواژه را تکرار کنید" name="password_bis" required id="id_password_bis">#}
{#    </td>#}
{{ form.password_bis }}
</tr>

<tr>
    <th><label for="id_identifyid" >شماره ملی:</label> </th>
{#    <td><input  type="text" placeholder="شماره ملی خود را وارد کنید" name="identifyid" required id="id_identifyid"#}
{#                maxlength="10" minlength="10" onkeyup="validateid()">#}
{#    </td>#}
{{ form.identifyid }}
</tr>
<tr>
    <th><label for="id_phone" >تلفن همراه :</label> </th>
    <td><input  type="text" placeholder="شماره تلفن خود را با قالب 09170000000 وارد کنید" name="phone"
                 id="id_phone" maxlength="11"
                minlength="11" accept="dig" onkeyup="validatephone()">
    </td>
</tr>

<tr>
    <th><label for="id_organisation">نام سازمان /شرکت:</label> </th>
{#    <td><input  type="text" placeholder="نام شرکت خود را وارد کنید" name="organisation"  id="id_organisation"#}
{#                maxlength="150">#}
{#    </td>#}
{{ form.organisation }}
</tr>


{% if registmode == "custom" %}
   <tr>
    <th><label for="id_max_apps">*تعداد سیستم های خبره:</label> </th>
    <td><input  type="number" placeholder="تعداد سیستم های خبره مورد نیاز را وارد کنید" name="max_apps" required id="id_max_apps" min="1">
   </tr>
    <tr>
    <th><label for="id_max_users">*تعداد کارکنان:</label> </th>
    <td><input  type="number" placeholder="تعداد کارکنان خود را وارد کنید" name="max_users" required id="id_max_users" min="1">
    </td>
    </tr>
{% endif %}
    <hr>
<p><input type="submit" class="registerbtn" value="ثبت عضویت" /></p>
<p>قبلا ثبت نام نموده اید؟ از اینجا
<a href="{% url 'signin' %}"> وارد شوید</a>
</p>
</form>

  </div>
<!--</div>-->
    <script>
    function validatephone() {
var p = document.getElementById('id_phone');
var numbers = /[0-9]/g;
        let isnum = /^\d*$/.test(pval);
        if (! p.value.match(numbers)){
            alert('فقط ورورد اعداد مجاز می باشد');
            p.innerText = '';
        }
    }

        function validateid() {
var idv = document.getElementById('id_identifyid');

var numbers = /[0-9]/g;
        let isnum = /^\d*$/.test(idvval);
        if (! idv.value.match(numbers)){
            alert('فقط ورورد اعداد مجاز می باشد');
            idv.innerText = '';
        }
    }

    </script>
{% endblock %}

ServiceUser/templates/ServiceUser/UserManagement/create_developer.html
{% extends "managementbase.html" %}
{% block title_html %}
ایجاد توسعه دهنده
{% endblock %}
{% block h1 %}
<!--<div class="container">-->
ایجاد توسعه دهنده
{% endblock %}
{% block article_content %}
<form method="post" action="{% url "RuleManager:create_developer" %}" >
<div class="infomsg">
    در این بخش سرپرستان سامانه می توانند کاربران توسعه دهنده سیستم را ایجاد و آنها را بعنوان زیرمجموعه یک سرپرست تعریف نمایند.
</div>
<br>

{% csrf_token %}
<!-- This line inserts a CSRF token. -->
<table>
<!--{{ form.as_table }}-->
<!-- This line displays lines of the form.-->
<thead>
<tr>
<td></td>
<td></td>
</tr>
</thead>
<tbody>
<tr>
    <td><label for="id_name">نام:</label></td>
   <td> <input class="inputdate" type="text" placeholder="نام را وارد کنید" name="name" maxlength="30" required id="id_name">
    </td>
</tr>
<tr>
    <td><label for="id_login">نام کاربری:</label> </td>
    <td><input class="inputdate" type="text" placeholder="نام کاربری را وارد کنید" name="login" maxlength="30" required id="id_login">
    </td>
</tr>
<tr>
    <td><label for="id_password">گذرواژه:</label> </td>
    <td><input class="inputdate" type="password" placeholder="گذرواژه را وارد کنید" name="password" required id="id_password">
    </td>
</tr>
<tr>
    <td><label for="id_supervisor">سرپرست:</label></td>
   <td> <select name="supervisor" required id="id_supervisor">
        <option value="" selected>---------</option>

    </select>
    </td>
</tr>
</tbody>
</table>
<p><input type="submit" class="registerbtn" value="ایجاد" /></p>

</form>
<!--</div>-->
{% endblock %}

ServiceUser/templates/ServiceUser/UserManagement/create_supervisor.html
{% extends "managementbase.html" %}
{% block title_html %}
ایجاد سرپرست
{% endblock %}
{% block h1 %}
ایجاد سرپرست
{% endblock %}
{% block article_content %}
<div class="infomsg">
    در این صفحه می توانید کاربران سرپرست سامانه را ایجاد نمایید.
    <br>
    سرپرستان سامانه می توانند عملیات ایجاد و حذف قوانین و حقایق و همچنین ایجاد کاربران عادی را انجام دهند.
</div>
<br>
<form method="post" action="{% url "RuleManager:create_supervisor" %}" >
{% csrf_token %}
<!-- This line inserts a CSRF token. -->
<table>
<!--{{ form.as_table }}-->
<thead>
<tr>
<td></td>
<td></td>
</tr>
</thead>

<tbody>
    <thead> </thead>
<tr>
    <td><label for="id_name">نام :</label></td>
    <td><input type="text" name="name" maxlength="30" required id="id_name" class="inputdate"></td>
</tr>
<tr>
    <td><label for="id_login">نام کاربری:</label></td>
    <td><input type="text" name="login" required id="id_login" class="inputdate"></td>
</tr>
<tr>
    <td><label for="id_email">رایانامه:</label></td>
    <td><input type="email" name="email" required id="id_email" class="inputdate"></td>
</tr>
<tr>
    <td><label for="id_specialisation">تخصص:</label></td>
    <td><input type="text" name="specialisation" required id="id_specialisation" class="inputdate"></td>
</tr>
<tr>
    <td><label for="id_password">گذرواژه:</label></td>
    <td><input type="password" name="password" required id="id_password" class="inputdate"></td>
</tr>
<tr>
    <td><label for="id_password_bis">تکرار گذرواژه:</label></td>
    <td><input type="password" name="password_bis" required id="id_password_bis" class="inputdate"></td>
</tr>

<!-- This line displays lines of the form.-->
</tbody>
</table>
<p><input type="submit" class="registerbtn" value="ایجاد" /></p>
</form>
{% endblock %}

ServiceUser/templates/ServiceUser/UserManagement/edit_appuser.html
{% extends "managementbase.html" %}
{% block title_html %}
ویرایش اطلاعات شخصی
{% endblock %}
{% block h1 %}
<span style="visibility: hidden">
ویرایش اطلاعات شخصی
</span>
{% endblock %}
{% block article_content %}
    <div class="centrecard" >
        <div class="contentheader">
            <h2>ویرایش اطلاعات شخصی
                <span style="font-size: medium; " class="w3-tooltip">
                        <i class="fa fa-info-circle helpicon fa-lg"></i>
                    <span class="w3-text w3-round-xlarge w3-tag w3-animate-opacity ">در این صفحه امکان ویرایش اطلاعات شخصی کاربر فراهم گردیده است
                    </span>
                </span>
            </h2>
        </div>
        <div class="contentcontainer" style="max-height: 600px; overflow: auto;">
            <div class="infomsg">
                <div class="infoheader">نکته</div>
                <p>
                    برای تغییر رمز عبور و ایمیل می توانید از منوی <a href="{% url 'ServiceUser:user_account2' %}">حساب کاربری</a> استفاده کنید.
                </p>
            </div>
            <form method="post" action="{% url "ServiceUser:edit_user"  %}" >
                <!-- This line inserts a CSRF token. -->
                {% csrf_token %}
                {% if form.errors.items %}
                    <hr>
                    <ul class="w3-panel w3-rightbar w3-border-red w3-pale-red" >
                        <strong>خطا!</strong><br>
                        {% for errfield,errmsg in form.errors.items %}
                            {{errfield}}:{{ errmsg }}
                        {% endfor %}
                    </ul>
                    <hr>
                {%endif%}
                <p>
                    <input  type="hidden" name="user_auth" value="{{ srvuser.pk }}" id="id_user_auth">
                    <!--<label for="id_login" >نام کاربری:-->
                    <!--    <input  type="text" name="login" value="{{ form.login.value }}" id="id_login">-->
                    <!--</label>-->
                    <label for="id_identifyid" >شماره ملی:
                        <input  type="text" name="identifyid" value="{{ form.identifyid.value }}"
                        id="id_identifyid" maxlength="10" minlength="10">
                    </label><br>
                    <label for="id_phone" >تلفن همراه :
                        <input  type="text" name="phone" value="{{ form.phone.value }}" id="id_phone"
                        maxlength="11" minlength="11">
                    </label><br>
                    <label for="id_organisation" >نام سازمان/شرکت:
                        <input  type="text" name="organisation" value="{{ form.organisation.value }}" id="id_organisation">
                    </label>
                    <br>
                </p>
                <hr>
                <p><input type="submit" class="registerbtn" value="ذخیره" ></p>
            </form>
        </div>
    </div>

{% endblock %}