Contract_Assistant/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', loginuser.verifyuser, name='signin'),
    path('signout/', logoutuser.finishconnection, name='sinout'),
    # path('register/', appuser.pricing, name='register'),
    path('register/', appuser.register2, name='register'),
    path('pricing/', appuser.pricing, name='princing'),
    path('RuleManager/', include('RuleManager.urls')),
    path('rulemanager/', include('RuleManager.urls')),
    path('ruleManager/', include('RuleManager.urls')),
    path('Rulemanager/', include('RuleManager.urls')),
    path('ServiceUser/', include('ServiceUser.urls')),
    # path('create-rule/', include('RuleManager.urls')),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('Expertsystem/', include('ExpertSystem.urls')),
    path('', include('ExpertSystem.urls')),
    path('plans/', include('plans.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/newpassword_reset_form.html',
        email_template_name = 'registration/newpassword_reset_email.html',
        subject_template_name= 'registration/newpassword_reset_subject.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/newpassword_reset_done.html')
         , name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/newpassword_reset_confirm.html')
         , name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/newpassword_reset_completed.html')
         , name='password_reset_complete'),
]

ExpertSystem/urls.py
from django.urls import  path
from . import forms, views
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ExpertSystem'
urlpatterns = [
    path('contractdemo', forms.initengine, name='expert_initial'),
    path('classiccontractdemo', forms.initengine_classic, name='expert_initial_classic'),
    path('update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    # path('', views.luncher, name = 'luncher'),
    # path('', login_required(PricingView.as_view(template_name='ExpertSystem/home.html')), name = 'luncher'),
    path('', PricingView.as_view(template_name='ExpertSystem/home.html'), name = 'luncher'),
    path("expert_contract/", forms.Creat_Expert, name='expert_contract'),
    path('ContractExpert/', forms.Creat_Expert, name='expert_contract'),
    path('expert_contract_byajax/', views.expert_contract_byajax, name='expert_contract_byajax'),
    path('rewindengine/', views.rewindengine, name='rewindengine'),
    path('update_facts/', views.update_facts, name='update_facts'),

    path('about/', views.about, name='about'),
    path('contact/', forms.contact, name='contact'),
    # path('RuleManager/', include('RuleManager.urls')),
]

RuleManager/urls.py
from django.urls import path, include
from . import forms, views
from django.views.generic.edit import CreateView
from RuleManager.models import Rules
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

app_name = 'RuleManager'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('update_rule_list/', views.filterrules, name='update_rule_list'),
    path('update_fact_list/', views.filterfacts, name='update_fact_list'),
    path('loginuser/', loginuser.verifyuser, name='loginuser'),
    path('register/', appuser.register, name='register'),
    path('logoutuser/', logoutuser.finishconnection, name='logoutuser'),
    # path('create_supervisor/', supervisor.create_supervisor, name='create_supervisor'),
    # path('create_developer/', developer.create_developer, name='create_developer'),
    path('<int:rule_id>/', views.detail, name='detail'),
    path('create_condition/', forms.create_condition, name='create_condition'),
    path('facts/create_fact/', forms.create_fact_by_model, name='create_fact'),
    path('update_facts/', views.update_facts, name='update_facts'),
    path('update_domains/', views.update_domains, name='update_domains'),
    path('create_rule_by_model/', forms.create_rule_by_model, name='create_rule_by_model'),
    path ('create_rule_cbv/', CreateView.as_view(model=Rules, fields= ['condition','consequence','pub_date','rule_type'],
        template_name="RuleManager/create_rule_by_model.html", success_url ='index'), name="create_rule_cbv"),
    path('edit_rule/<int:rule_id>/', forms.edit_rule_by_index, name='edit_rule'),
    path('delete_rule/<int:rul_ind>/', views.delete_rule_by_index, name='delete_rule'),
    path('facts/', views.factlist, name='factlist'),
    path('facts/<int:fact_ind>/', views.factdetail, name='factdetail'),
    path('facts/edit_fact/<int:fact_ind>/', forms.edit_fact_by_index, name='edit_fact'),
    path('facts/delete_fact/<int:fact_ind>/', views.delete_fact_by_index, name='delete_fact'),
    path('domains/', views.domainlist, name='domainlist'),
    path('domains/<int:dom_ind>/', views.domaindetail, name='domaindetail'),
    path('domains/create_domain/', forms.create_domain_by_model, name='create_domain'),
    path('domains/edit_domain/<int:dom_ind>/', forms.edit_domain_by_index, name='edit_domain'),
    path('domains/delete_domain/<int:dom_ind>/', views.delete_domain_by_index, name='delete_domain'),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('ExpertSystem/', include('ExpertSystem.urls')),
    path('loginuser/expertsystem/', include('ExpertSystem.urls')),
     path('loginuser/Expertsystem/', include('ExpertSystem.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_form.html')
    #      , name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_done.html')
    #      , name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_confirm.html')
    #      , name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_complete.html')
    #      , name='password_reset_complete'),

]

ServiceUser/urls.py
from django.urls import path, include
from . import forms, views
from .UserManagement import loginuser, appuser
from RuleManager import views as Rule_views
from RuleManager import forms as Rule_forms
from .messagemanager import restore_default_messages
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ServiceUser'
urlpatterns = [
    # *** auth user urls ***
    path('create_user/', forms.create_user, name='create_user'),
    path('create_user/result', views.create_user_result, name='create_user-result'),
    path('edit_user/', appuser.edit_user, name='edit_user'),
    # *** auth user urls ***

    # *** supervisor urls ***
    path('supervisors/', views.supervisorlist, name='supervisorlist'),
    path('supervisors/create/', forms.create_supervisor, name='create_supervisor'),
    path('supervisors/<int:sup_id>/', views.supervisor_detail, name='supervisordetail'),
    path('supervisors/edit/<int:sup_id>/', forms.edit_supervisor_by_index, name='edit_supervisor'),
    path('supervisors/delete/<int:sup_id>/', views.delete_supervisor_by_index, name='delete_supervisor'),
    # *** supervisor urls ***

    # *** developer urls ***
    path('developers/', views.developerlist, name='developerlist'),
    path('developers/create/', forms.create_developer, name='create_developer'),
    path('developers/<int:dev_id>/', views.developer_detail, name='developerdetail'),
    path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** developer urls ***

    # *** appuser urls ***
    path('plans/', include('plans.urls')),
    # path('', views.dashboard2, name='user_dashboard'),
    path('', views.dashboard, name='user_dashboard2'),
    path('noaccess/', views.permission, name='Forbidden_content'),
    path('registration/<mode>/', appuser.register, name='registration'),
    # path('registration/', appuser.register2, name='registration'),
    path('registration/activate/<uidb64>/<token>/', appuser.activate, name='activate'),
    # path('account/', views.account, name='user_account'),
    path('account/',login_required(PricingView.as_view(template_name='ServiceUser/useraccount2.html')) , name='user_account2'),
    path('account/upgrade/', forms.upgradeaccount, name='upgrade_user_account'),
    path('account/limitations/', views.accountlimit, name='accountlimit'),
    path('payments/', views.paymentlist, name='user_payments'),
    path('staffs/', views.userstaffs, name='user_staffs'),
    path('staffs/add/', forms.create_employee, name='create_userstaff'),
    path('staffs/<int:staff_id>/edit/',forms.edit_employee_by_index, name='edit_userstaff'),
    path('staffs/<int:staff_id>/delete/', views.delete_employee_by_index, name='delete_userstaff'),
    path('staffs/<int:staff_id>/detail/', views.staffdetail, name='user_staffdetail'),
    path('experts/', views.userexperts, name='user_expertmodel'),
    path('experts/config', forms.configengine, name='engineconfig'),
    path('experts/config/restore', restore_default_messages, name='restoredefaults'),
    path('experts/add/', forms.create_expertmodel, name='create_expertmodel'),
    path('experts/<int:exp_id>/', views.userexpertdetail, name='user_expertdetail'),
    path('experts/<int:exp_id>/controlpanel/', views.controlpanel, name='controlpanel'),
    path('experts/<int:exp_id>/update_facts/', views.update_domain_facts, name='update_facts'),
    path('experts/<int:exp_id>/edit/', forms.userexpertedit, name='user_expert_edit'),
    path('experts/<int:exp_id>/delete/', views.userexpertdelete, name='user_expert_delete'),
    path('experts/<int:exp_id>/start/', forms.userexpertstart, name='user_expert_start'),
    path('experts/<int:exp_id>/start/update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    path('experts/<int:exp_id>/startclassic/', forms.userexpertstartclassic, name='user_expert_start_classic'),
    path('experts/<int:exp_id>/startclassic/update_detailfacts/', forms.update_detailfacts, name='update_classic_detailfacts'),
    path('experts/<int:exp_id>/RuleManager/', Rule_views.index, name='user_expertrules'),
    path('experts/<int:exp_id>/RuleManager/create_condition', Rule_forms.create_condition,
         name='user_expert_createcondition'),
    path('experts/<int:exp_id>/RuleManager/controlpanel', Rule_views.controlpanel,
         name='user_expert_controlpanel'),
    path('experts/<int:exp_id>/RuleManager/add/',Rule_forms.create_rule_by_model ,
         name='user_expertnewrule'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/',Rule_views.detail ,
         name='user_expertrule_detail'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/edit/',Rule_forms.edit_rule_by_index,
         name='user_expertrule_edit'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/delete/',Rule_views.delete_rule_by_index,
         name='user_expertrule_delete'),
    path('experts/<int:exp_id>/RuleManager/facts',Rule_views.factlist , name='user_expertfacts'),
    path('experts/<int:exp_id>/RuleManager/facts/add',Rule_forms.create_fact_by_model ,
         name='user_expertnewfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload',Rule_forms.upload_fact_file ,
         name='user_expert_uploadfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload/result',Rule_views.upload_fact_result ,
         name='factupload_result'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/',Rule_views.factdetail ,
         name='user_expertfact_detail'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/edit/',Rule_forms.edit_fact_by_index ,
         name='user_expertfact_edit'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/delete/',Rule_views.delete_fact_by_index ,
         name='user_expertfact_delete'),
    path('experts/<int:exp_id>/RuleManager/domains', Rule_views.domainlist, name='user_expertdomains'),
    path('<username>/experts/<int:exp_id>/RuleManager/domains/add', Rule_forms.create_domain_by_model,
         name='user_expertnewdomain'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/', Rule_views.domaindetail,
         name='user_expertdomain_detail'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/edit/', Rule_forms.edit_domain_by_index,
         name='user_expertdomain_edit'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/delete/', Rule_views.delete_domain_by_index,
         name='user_expertdomain_delete'),
    path('experts/<int:exp_id>/RuleManager/domains/add',Rule_forms.create_domain_by_model ,
         name='user_expertnewdomain'),

    # path('<username>/experts/create', views.developer_detail, name='developerdetail'),
    # path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    # path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** appuser urls ***

]

zarinpal/urls.py
# Github.com/Rasooll
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('', views.verify , name='verify'),
]

ExpertSystem/models.py
from django.db import models
from ServiceUser.models import App_User, Employee
# from RuleManager.models import Rules, Facts
# Create your models here.
class Comments(models.Model):

    name = models.CharField( max_length=255, blank=False )
    email=models.EmailField(max_length=255, blank=False )
    subject = models.TextField(max_length=3000, blank=False )

    def __str__(self):
        return (self.subject[:100] + '...') if len(self.subject) > 100 else self.subject

class Expertmodel(models.Model):
    _PUB = 'PUBLIC'
    _USER = 'RESTRICTED'
    _ACCESS = [(_PUB, 'دسترسی عمومی'),(_USER, 'دسترسی فقط برای کاربران')]
    name = models.CharField(max_length=200, verbose_name='نام سیستم خبره')
    appuser = models.ForeignKey('ServiceUser.App_User', on_delete=models.DO_NOTHING, related_name='user', verbose_name='مالک سیستم خبره')
    accesstype = models.CharField(choices=_ACCESS, default=_PUB,max_length=10,  verbose_name='نحوه دسترسی به سیستم خبره')
    # authorizedusers = models.ManyToManyField(Employee,related_name='allowedusers_fiels',
    #                                          limit_choices_to=Employee.objects.filter(manager=appuser))



    def get_related_facts(self):
        fact_set =self.factowner_field.all()
        if fact_set.count():
            return fact_set
        else:
            return None

    def get_related_rules(self):
        rule_set =self.ruleowner_field.all()
        if rule_set.count():
            return rule_set
        else:
            return None

    def get_related_domains(self):
        domain_set = self.domainowner_field.all()
        if domain_set.count():
            return domain_set
        else:
            return None

    def __str__(self):
        return self.name

    def getowneruser(self):
        return self.appuser.user_auth.username

ServiceUser/templates/ServiceUser/create_expertmodel.html
{% extends "managementbase.html" %}
{% block title_html %}
ایجاد سامانه هوشمند
{% endblock %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
{% block h1 %}
    <span style="visibility: hidden">
ایجاد سامانه هوشمند
    </span>
{% endblock %}
{% block article_content %}
    <div class="centrecard" >
        <div class="contentheader">
            <h2>ایجاد سیستم خبره
                <span style="font-size: medium; " class="w3-tooltip">
                        <i class="fa fa-info-circle helpicon fa-lg"></i>
                    <span class="w3-text w3-round-xlarge w3-tag w3-animate-opacity ">در این صفحه می توانید سامانه هوشمند جدید را ایجاد نمایید.
                    </span>
                </span>
            </h2>
        </div>
        <div class="contentcontainer" style="max-height: 600px; overflow: auto;">
            <form method="post" action="{% url "ServiceUser:create_expertmodel" %}" >
                <!-- This line inserts a CSRF token. -->
                {% csrf_token %}
                <div class="alerttext">
                    <div class="alertheader">توجه</div>
                    <p>ورود اطلاعاتی که با رنگ قرمز مشخص شده اند الزامی می باشد.</p>
                </div>
                <hr>
                <div class="errorlist" style="direction: ltr; padding-left: 10px">
                    {% for errfield,errmsg in form.errors.items %}
                        {{ errfield }}: {{ errmsg }}
                    {% endfor %}
                </div>
            <p>
                <label for="id_appuser">*مالک :
                    {{ form.appuser }}
                </label><br>
                <label for="id_name">*نام سیستم خبره:
                    {{ form.name }}
                </label><br>
                <label for="id_accesstype">*نحوه دسترسی به سیستم خبره:
                    {{ form.accesstype }}
                </label>
            </p>
                <hr>
                <p><input type="submit" class="registerbtn" value="ایجاد" /></p>
            </form>
            <!--</div>-->
            <script>
                function newuserpop() {
                    window.open("{% url 'ServiceUser:create_user' %}",'popup','width=600,height=600');
                    return false;
                }
            </script>
        </div>
    </div>

{% endblock %}

ServiceUser/templates/ServiceUser/expertfacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ServiceUser/templates/ServiceUser/moderntopnav.html
<!--*************** IN TOPNAV MENU-START ***************-->
{% load static %}

<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
div.card {

  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);

}

</style>

<div class="w3-top w3-card-4">
<div class="w3-bar w3-blue-grey  w3-large">
  <div class="w3-dropdown-hover w3-right">
    <span class="w3-button w3-hover-pale-green w3-green  "><i class="fa fa-diamond" aria-hidden="true"></i>سامانه هوشمند <i class="fa fa-caret-down"></i></apan>
     <div class="w3-dropdown-content w3-bar-block w3-card-4 w3-right ">
        <a class="w3-bar-item w3-button  w3-right" href="{% url 'ExpertSystem:expert_initial' %}">نسخه مدرن</a>
        <a class="w3-bar-item w3-button  w3-right" href="{% url 'ExpertSystem:expert_initial_classic' %}">نسخه کلاسیک</a>
     </div>
  </div>
  <div class="w3-dropdown-hover w3-right w3-hide-small  ">
    <span class="w3-button "><i class="fa fa-cog" aria-hidden="true"></i> داشبورد مدیریتی <i class="fa fa-caret-down"></i></span>
     <div class="w3-dropdown-content w3-bar-block w3-card-4 w3-hide-small  w3-right">
        <a class="w3-bar-item w3-button  w3-hide-small w3-right" href="{% url 'ServiceUser:user_expertmodel'  %}">مدیریت سامانه های هوشمند</a>
        <a class="w3-bar-item w3-button  w3-hide-small w3-right" href="{% url 'ServiceUser:user_account2'  %}">مدیریت حساب</a>
        <a class="w3-bar-item w3-button  w3-hide-small w3-right" href="{% url 'ServiceUser:user_staffs'  %}">مدیریت کاربران</a>
     </div>
  </div>
  <a class="w3-bar-item w3-button  w3-right w3-hide-small " href="{% url "ExpertSystem:about"%}"><i class="fa fa-info"></i>  درباره</a>
  <a class="w3-bar-item w3-button  w3-right w3-hide-small " href="{% url "ExpertSystem:contact"%}"><i class="fa fa-envelope"></i> تماس با ما</a>
  <a class="w3-bar-item w3-button  w3-right w3-hide-small w3-hover-pale-blue w3-blue" href="{% url 'ExpertSystem:luncher' %}" ><i class="fa fa-home"></i> خانه</a>
  <a class="w3-bar-item w3-button  w3-hide-small" href="{% url "register"%}" class="left" id="id_register"><i class="fa fa-user-plus" aria-hidden="true"></i>
          ثبت نام</a>
  <a  class="w3-bar-item w3-button  w3-hide-small" id="id_signin"><i class="fa fa-sign-in"></i> ورود</a>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-left w3-hide-large w3-hide-medium" onclick="Collmenu()">
      <i class="fa fa-bars"></i></a>


<div id="collapsable" class="w3-bar-block w3-hide w3-hide-large w3-hide-medium  w3-right w3-light-grey">
  <div class="w3-dropdown-hover  w3-right  w3-right ">
    <button class="w3-button w3-bottombar "><i class="fa fa-cog" aria-hidden="true"></i> داشبورد مدیریتی <i class="fa fa-caret-down"></i></button>
     <div class="w3-dropdown-content w3-bar-block w3-card-4  w3-right">
        <a class="w3-bar-item w3-button  w3-right  w3-right" href="{% url 'ServiceUser:user_expertmodel'  %}">مدیریت سامانه های هوشمند</a>
        <a class="w3-bar-item w3-button  w3-right  w3-right" href="{% url 'ServiceUser:user_account2'  %}">مدیریت حساب</a>
        <a class="w3-bar-item w3-button  w3-right  w3-right" href="{% url 'ServiceUser:user_staffs'  %}">مدیریت کاربران</a>
     </div>
  </div>
  <a class="w3-bar-item w3-button  w3-right  w3-right" href="{% url "ExpertSystem:about"%}"><i class="fa fa-info"></i>  درباره</a>
  <a class="w3-bar-item w3-button  w3-right  w3-right" href="{% url "ExpertSystem:contact"%}"><i class="fa fa-envelope"></i> تماس با ما</a>
  <a class="w3-bar-item w3-button  w3-right  w3-right w3-hover-pale-blue w3-blue" href="{% url 'ExpertSystem:luncher' %}" ><i class="fa fa-home"></i> خانه</a>
  <a class="w3-bar-item w3-button  w3-right" href="{% url "register"%}" class="left" id="id_register"><i class="fa fa-user-plus" aria-hidden="true"></i>
          ثبت نام</a>
  <a  class="w3-bar-item w3-button  w3-right" id="id_signin"><i class="fa fa-sign-in"></i> ورود</a>
</div>
</div>
</div>
<script>
function Collmenu() {
  var x = document.getElementById("collapsable");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

function manageuser(user)
{
    if(user!=='not_signed_in' && user!='')
    {
        document.getElementById('id_signin').innerText = user;
        document.getElementById('id_signin').style.textShadow = "2px 2px 4px #000000";
        document.getElementById('id_signin').style.borderBottomStyle = "outset  ";
        document.getElementById('id_signin').style.borderColor='black';
        document.getElementById('id_signin').style.borderBottomWidth="medium";
        document.getElementById('id_register').remove();
    }else
        {
        var sinin_link = document.getElementById('id_signin');
        sinin_link.innerHtml = '<i class="fa fa-sign-in"></i> ورود';
        sinin_link.href = " {% url 'signin' %}";
        var navlinks = document.getElementById('myTopnav');
        var len = navlinks.children.length;
        if(navlinks.children[len-1].innerText!=='ثبت نام')
        {
            var reglink = document.createElement("a");               // Create a <a> element
            reglink.innerText = "ثبت نام";
            reglink.href= '{% url "register"%}';
            reglink.className = "left";
            reglink.id = 'id_register';
            navlinks.splice(len-1, 0, reglink);
        }
    }
}

var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("activecontent");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    }
  });
}
</script>

ServiceUser/templates/ServiceUser/topnavmenu.html
<!--*************** IN TOPNAV MENU-START ***************-->
{% load static %}

<link href="{% static "/ExpertSystem/css/expertstyle.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "/ExpertSystem/css/menustyle.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "/UserManagement/css/managementstyle.css" %}" rel="stylesheet" type="text/css" />
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="topnav" id="myTopnav" >
        <div class="dropdown">
            <button class="dropbtn" style="border-bottom: 5px solid mediumseagreen; color: black"><i class="fa fa-diamond" aria-hidden="true"></i>
                سامانه هوشمند
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'ExpertSystem:expert_initial' %}">نسخه مدرن</a>
                <a href="{% url 'ExpertSystem:expert_initial_classic' %}">نسخه کلاسیک</a>
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn" style="color: black"><i class="fa fa-cog" aria-hidden="true"></i>
            تنظیمات
            <i class="fa fa-caret-down"></i>
        </button>
            <div class="dropdown-content">
                <a href="{% url 'ServiceUser:user_dashboard2'  %}">داشبورد مدیریتی</a>
                <hr>
                <a href="{% url 'ServiceUser:user_expertmodel'  %}">مدیریت سامانه های هوشمند</a>
                <a href="{% url 'ServiceUser:user_account2'  %}">مدیریت حساب</a>
                <a href="{% url 'ServiceUser:user_staffs'  %}">مدیریت کاربران</a>
            </div>
        </div>
        <a href="{% url 'ExpertSystem:about'%}"><i class="fa fa-info"></i>  درباره</a>
        <a href="{% url 'ExpertSystem:contact'%}"><i class="fa fa-envelope"></i> تماس با ما</a>
        <a href="{% url 'register'%}" class="left" id="id_register"><i class="fa fa-user-plus" aria-hidden="true"></i>
          ثبت نام</a>
        <a class="left" id="id_signin"><i class="fa fa-sign-in"></i> ورود</a>
        <a href="{% url 'ExpertSystem:luncher' %}" style="border-bottom: 5px solid deepskyblue;"><i class="fa fa-home"></i> خانه</a>
        <a href="#" class="icon" onclick="responsemenu()">
            <i class="fa fa-bars"></i>
        </a>
</div>





<!--*************** IN TOPNAV MENU-END ***************-->