Contract_Assistant/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', loginuser.verifyuser, name='signin'),
    path('signout/', logoutuser.finishconnection, name='sinout'),
    # path('register/', appuser.pricing, name='register'),
    path('register/', appuser.register2, name='register'),
    path('pricing/', appuser.pricing, name='princing'),
    path('RuleManager/', include('RuleManager.urls')),
    path('rulemanager/', include('RuleManager.urls')),
    path('ruleManager/', include('RuleManager.urls')),
    path('Rulemanager/', include('RuleManager.urls')),
    path('ServiceUser/', include('ServiceUser.urls')),
    # path('create-rule/', include('RuleManager.urls')),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('Expertsystem/', include('ExpertSystem.urls')),
    path('', include('ExpertSystem.urls')),
    path('plans/', include('plans.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/newpassword_reset_form.html',
        email_template_name = 'registration/newpassword_reset_email.html',
        subject_template_name= 'registration/newpassword_reset_subject.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/newpassword_reset_done.html')
         , name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/newpassword_reset_confirm.html')
         , name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/newpassword_reset_completed.html')
         , name='password_reset_complete'),
]

RuleManager/urls.py
from django.urls import path, include
from . import forms, views
from django.views.generic.edit import CreateView
from RuleManager.models import Rules
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

app_name = 'RuleManager'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('update_rule_list/', views.filterrules, name='update_rule_list'),
    path('update_fact_list/', views.filterfacts, name='update_fact_list'),
    path('loginuser/', loginuser.verifyuser, name='loginuser'),
    path('register/', appuser.register, name='register'),
    path('logoutuser/', logoutuser.finishconnection, name='logoutuser'),
    # path('create_supervisor/', supervisor.create_supervisor, name='create_supervisor'),
    # path('create_developer/', developer.create_developer, name='create_developer'),
    path('<int:rule_id>/', views.detail, name='detail'),
    path('create_condition/', forms.create_condition, name='create_condition'),
    path('facts/create_fact/', forms.create_fact_by_model, name='create_fact'),
    path('update_facts/', views.update_facts, name='update_facts'),
    path('update_domains/', views.update_domains, name='update_domains'),
    path('create_rule_by_model/', forms.create_rule_by_model, name='create_rule_by_model'),
    path ('create_rule_cbv/', CreateView.as_view(model=Rules, fields= ['condition','consequence','pub_date','rule_type'],
        template_name="RuleManager/create_rule_by_model.html", success_url ='index'), name="create_rule_cbv"),
    path('edit_rule/<int:rule_id>/', forms.edit_rule_by_index, name='edit_rule'),
    path('delete_rule/<int:rul_ind>/', views.delete_rule_by_index, name='delete_rule'),
    path('facts/', views.factlist, name='factlist'),
    path('facts/<int:fact_ind>/', views.factdetail, name='factdetail'),
    path('facts/edit_fact/<int:fact_ind>/', forms.edit_fact_by_index, name='edit_fact'),
    path('facts/delete_fact/<int:fact_ind>/', views.delete_fact_by_index, name='delete_fact'),
    path('domains/', views.domainlist, name='domainlist'),
    path('domains/<int:dom_ind>/', views.domaindetail, name='domaindetail'),
    path('domains/create_domain/', forms.create_domain_by_model, name='create_domain'),
    path('domains/edit_domain/<int:dom_ind>/', forms.edit_domain_by_index, name='edit_domain'),
    path('domains/delete_domain/<int:dom_ind>/', views.delete_domain_by_index, name='delete_domain'),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('ExpertSystem/', include('ExpertSystem.urls')),
    path('loginuser/expertsystem/', include('ExpertSystem.urls')),
     path('loginuser/Expertsystem/', include('ExpertSystem.urls')),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_form.html')
    #      , name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_done.html')
    #      , name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_confirm.html')
    #      , name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='RuleManager/UserManagement/registration/newpassword_reset_complete.html')
    #      , name='password_reset_complete'),

]

ServiceUser/urls.py
from django.urls import path, include
from . import forms, views
from .UserManagement import loginuser, appuser
from RuleManager import views as Rule_views
from RuleManager import forms as Rule_forms
from .messagemanager import restore_default_messages
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ServiceUser'
urlpatterns = [
    # *** auth user urls ***
    path('create_user/', forms.create_user, name='create_user'),
    path('create_user/result', views.create_user_result, name='create_user-result'),
    path('edit_user/', appuser.edit_user, name='edit_user'),
    # *** auth user urls ***

    # *** supervisor urls ***
    path('supervisors/', views.supervisorlist, name='supervisorlist'),
    path('supervisors/create/', forms.create_supervisor, name='create_supervisor'),
    path('supervisors/<int:sup_id>/', views.supervisor_detail, name='supervisordetail'),
    path('supervisors/edit/<int:sup_id>/', forms.edit_supervisor_by_index, name='edit_supervisor'),
    path('supervisors/delete/<int:sup_id>/', views.delete_supervisor_by_index, name='delete_supervisor'),
    # *** supervisor urls ***

    # *** developer urls ***
    path('developers/', views.developerlist, name='developerlist'),
    path('developers/create/', forms.create_developer, name='create_developer'),
    path('developers/<int:dev_id>/', views.developer_detail, name='developerdetail'),
    path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** developer urls ***

    # *** appuser urls ***
    path('plans/', include('plans.urls')),
    # path('', views.dashboard2, name='user_dashboard'),
    path('', views.dashboard, name='user_dashboard2'),
    path('noaccess/', views.permission, name='Forbidden_content'),
    path('registration/<mode>/', appuser.register, name='registration'),
    # path('registration/', appuser.register2, name='registration'),
    path('registration/activate/<uidb64>/<token>/', appuser.activate, name='activate'),
    # path('account/', views.account, name='user_account'),
    path('account/',login_required(PricingView.as_view(template_name='ServiceUser/useraccount2.html')) , name='user_account2'),
    path('account/upgrade/', forms.upgradeaccount, name='upgrade_user_account'),
    path('account/limitations/', views.accountlimit, name='accountlimit'),
    path('payments/', views.paymentlist, name='user_payments'),
    path('staffs/', views.userstaffs, name='user_staffs'),
    path('staffs/add/', forms.create_employee, name='create_userstaff'),
    path('staffs/<int:staff_id>/edit/',forms.edit_employee_by_index, name='edit_userstaff'),
    path('staffs/<int:staff_id>/delete/', views.delete_employee_by_index, name='delete_userstaff'),
    path('staffs/<int:staff_id>/detail/', views.staffdetail, name='user_staffdetail'),
    path('experts/', views.userexperts, name='user_expertmodel'),
    path('experts/config', forms.configengine, name='engineconfig'),
    path('experts/config/restore', restore_default_messages, name='restoredefaults'),
    path('experts/add/', forms.create_expertmodel, name='create_expertmodel'),
    path('experts/<int:exp_id>/', views.userexpertdetail, name='user_expertdetail'),
    path('experts/<int:exp_id>/controlpanel/', views.controlpanel, name='controlpanel'),
    path('experts/<int:exp_id>/update_facts/', views.update_domain_facts, name='update_facts'),
    path('experts/<int:exp_id>/edit/', forms.userexpertedit, name='user_expert_edit'),
    path('experts/<int:exp_id>/delete/', views.userexpertdelete, name='user_expert_delete'),
    path('experts/<int:exp_id>/start/', forms.userexpertstart, name='user_expert_start'),
    path('experts/<int:exp_id>/start/update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    path('experts/<int:exp_id>/startclassic/', forms.userexpertstartclassic, name='user_expert_start_classic'),
    path('experts/<int:exp_id>/startclassic/update_detailfacts/', forms.update_detailfacts, name='update_classic_detailfacts'),
    path('experts/<int:exp_id>/RuleManager/', Rule_views.index, name='user_expertrules'),
    path('experts/<int:exp_id>/RuleManager/create_condition', Rule_forms.create_condition,
         name='user_expert_createcondition'),
    path('experts/<int:exp_id>/RuleManager/controlpanel', Rule_views.controlpanel,
         name='user_expert_controlpanel'),
    path('experts/<int:exp_id>/RuleManager/add/',Rule_forms.create_rule_by_model ,
         name='user_expertnewrule'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/',Rule_views.detail ,
         name='user_expertrule_detail'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/edit/',Rule_forms.edit_rule_by_index,
         name='user_expertrule_edit'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/delete/',Rule_views.delete_rule_by_index,
         name='user_expertrule_delete'),
    path('experts/<int:exp_id>/RuleManager/facts',Rule_views.factlist , name='user_expertfacts'),
    path('experts/<int:exp_id>/RuleManager/facts/add',Rule_forms.create_fact_by_model ,
         name='user_expertnewfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload',Rule_forms.upload_fact_file ,
         name='user_expert_uploadfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload/result',Rule_views.upload_fact_result ,
         name='factupload_result'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/',Rule_views.factdetail ,
         name='user_expertfact_detail'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/edit/',Rule_forms.edit_fact_by_index ,
         name='user_expertfact_edit'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/delete/',Rule_views.delete_fact_by_index ,
         name='user_expertfact_delete'),
    path('experts/<int:exp_id>/RuleManager/domains', Rule_views.domainlist, name='user_expertdomains'),
    path('<username>/experts/<int:exp_id>/RuleManager/domains/add', Rule_forms.create_domain_by_model,
         name='user_expertnewdomain'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/', Rule_views.domaindetail,
         name='user_expertdomain_detail'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/edit/', Rule_forms.edit_domain_by_index,
         name='user_expertdomain_edit'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/delete/', Rule_views.delete_domain_by_index,
         name='user_expertdomain_delete'),
    path('experts/<int:exp_id>/RuleManager/domains/add',Rule_forms.create_domain_by_model ,
         name='user_expertnewdomain'),

    # path('<username>/experts/create', views.developer_detail, name='developerdetail'),
    # path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    # path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** appuser urls ***

]

zarinpal/urls.py
# Github.com/Rasooll
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('', views.verify , name='verify'),
]

RuleManager/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from ExpertSystem.models import Expertmodel

class Rules(models.Model):
    condition = models.TextField(verbose_name='شرط قانون',help_text="شرط را وارد کنید")
    pub_date = models.DateTimeField(default=now , verbose_name='تاریخ انتشار',
                            help_text ='تاریخ انتشار قانون را وارد کنید')
    consequence = models.ForeignKey('Facts', on_delete=models.CASCADE, related_name='consequence_field',
                            verbose_name='نتیجه قانون',help_text='نتیجه قانون را انتخاب کنید')
    domain = models.ForeignKey('Domain', on_delete=models.CASCADE, related_name='ruledomian_field',default=1,
                               verbose_name='نام حوزه دانش', help_text='حوزه دانش را انتخاب کنید')
    ownerexpert = models.ForeignKey(Expertmodel, on_delete=models.CASCADE, related_name='ruleowner_field', default=1,
                verbose_name='سیستم خبره', help_text='سیستم خبره ای که این قانون مربوط به آن است را انتخاب نمایید')
    class Meta:
        db_table = "RuleManager_rules"

    def __str__(self):
        return str(self.condition)+'==>'+str(self.consequence)



class Facts(models.Model):

    _YESNO = 'Y/N'
    _EXPLANING = 'EXP'
    _FACT_TYPE = [
        (_YESNO, 'خیر/بلی'),
        (_EXPLANING, 'تشریحی'),]
    _CONSEQUENCE = 'CONS'
    _CONDITION = 'COND'
    _SUBJECT = 'SUBJ'
    _FACT_EFFECT = [
        (_CONDITION, 'حقیقت بیان کننده ویژگی'),
        (_CONSEQUENCE, 'حقیقت بیان کننده نتیجه گیری'),
        (_SUBJECT,'حقیقت بیان کننده موضوع')
    ]
    fact_effect = models.CharField(max_length=4, choices=_FACT_EFFECT, default=_CONDITION,
                help_text='محدوده اثر حقیقت را انتخاب کنید',verbose_name='اثر حقیقت')
    fact = models.CharField(max_length=2000, blank=False, unique=True,
                help_text=' حقیقت را در حداکثر 2000 کلمه وارد کنید', verbose_name=' حقیقت')
    fact_type = models.CharField(max_length=3, choices=_FACT_TYPE, default=_YESNO,
                help_text=' نوع حقیقت را انتخاب کنید', verbose_name='نوع حقیقت')
    domain = models.ForeignKey('Domain',on_delete=models.CASCADE,related_name='factdomian_field',default=1,
                help_text=' حوزه دانش حقیقت را انتخاب کنید', verbose_name=' حوزه دانش')
    ownerexpert = models.ForeignKey(Expertmodel, on_delete=models.CASCADE, related_name='factowner_field', default=1,
            verbose_name='سیستم خبره', help_text='سیستم خبره ای که این حقیقت مربوط به آن است را انتخاب نمایید')

    def __str__(self):
        return self.fact


class Domain(models.Model):
    desc = models.TextField(max_length=300,blank=False,verbose_name='شرح حوزه دانش',
                help_text='توصیف مختصری از حوزه دانش مرتبط در حداکثر 300 حرف را وارد کنید')
    # brief = models.CharField(max_length=50,blank=False,unique=True, verbose_name='کد حوزه دانش',
                # help_text='کد مخفف حوزه دانش را با حروف انگلیسی در حداکثر 50 حرف وارد نمایید')
    ownerexpert = models.ForeignKey(Expertmodel, on_delete=models.CASCADE, related_name='domainowner_field', default=1,
                verbose_name='سیستم خبره', help_text='سیستم خبره ای که این حوزه دانش مربوط به آن است را انتخاب نمایید')

    def __str__(self):
        return (self.desc[:50] + '...') if len(self.desc) > 50 else self.desc

RuleManager/templates/RuleManager/delete_rule.html
{% extends "base.html" %}
{% block title_html %}
حذف قانون
{% endblock %}
{% load RuleManager_filters %}
{% block h1 %}
<span style="visibility: hidden">
حذف قانون
 </span>
{% endblock %}

{% block article_content %}
    <div class="w3-card-4 w3-round w3-content" >
        <div class="contentheader" style="margin-bottom: 16px">
            <h2>حذف قانون
                <span style="font-size: medium; " class="w3-tooltip">
                        <i class="fa fa-info-circle helpicon fa-lg"></i>
                    <span class="w3-text w3-round-xlarge w3-tag w3-animate-opacity ">در این صفحه قانون انتخاب شده قابل حذف می باشد.
                    </span>
                </span>
            </h2>
    </div>
    <div class="w3-container" >
<form method="post" action="{% url "ServiceUser:user_expertrule_delete" exp_id rule.pk %}" >
{% csrf_token %}
<!-- This line inserts a CSRF token. -->
<table>
    <th >
        شناسه:
    </th>
    <th>
        شرط:
    </th>
    <th>
        نتیجه:
    </th>

<tbody>
<tr>
    <td >
        {{ rule.pk }}
    </td>
    <td>
        {{ rule.condition|topersian }}
    </td>
    <td>
        {{ rule.consequence }}
    </td>
</tr>
</tbody>
</table>
<hr>
<div class="alerttext">
    <div class="alertheader">اخطار</div>
    <p>
        آیا از حذف این قانون اطمینان دارید؟
        این عمل قابل برگشت نمی باشد
       </p>
</div>
<div class="w3-container ">
        <input type="submit" value="تایید"  class="button button1 w3-pale-red w3-hover-red" >
        <input type="button" value="انصراف" class="button button1 w3-pale-green w3-hover-green  w3-mobile"  onclick="window.location.href=
                '{% url 'ServiceUser:user_expertrules' exp_id %}' "/>
</div>
<script>
function deleterule() {
window.location.href = "{% url "ServiceUser:user_expertrule_delete" exp_id rule.pk %}" ;
}
</script>

</form>
    </div>
</div>
{% endblock %}

RuleManager/templates/RuleManager/edit_rule.html
{% extends "base.html" %}
{% block title_html %}
ویرایش قانون
{% endblock %}
{% block h1 %}
<span style="visibility: hidden">
ویرایش قانون
</span>
{% endblock %}
{% block article_content %}
    <div class="w3-content w3-card-4 w3-light-gray w3-round" >
        <div class="contentheader" style="margin-bottom: 16px">
            <h2>ویرایش قانون
                <span style="font-size: medium; " class="w3-tooltip">
                        <i class="fa fa-info-circle helpicon fa-lg"></i>
                    <span class="w3-text w3-round-xlarge w3-tag w3-animate-opacity ">
                        دراین بخش امکان اصلاح کلیه قسمت های قانون وجود دارد.
                    </span>
                </span>
            </h2>
        </div>
    <div class="w3-container " >
        {% load jalali_tags %}
<form method="post" action="{% url "ServiceUser:user_expertrule_edit" exp_id rule.pk %}" onload="initform()">
{% csrf_token %}
<script>
    rule_id = '{{ rule.pk }}';
    exp_id = '{{ ownerexpert.id }}';
    curr_user = '{{ user.username }}';
</script>
{% load static %}
<script src="{% static 'RuleManager/javascript/rulescripts.js' %}" defer></script>
{{ form.non_field_errors }}
                {% for field in form %}
                        {% if field.errors %}
                            <div class="alerttext">
                         {{ field.label }}:{{ field.errors }}
                            </div>
                        {% endif %}
                {% endfor %}
<div class="notemsg">
<div class="noteheader">نکته</div>
<p> برای ویرایش شرط از دکمه انتخاب و ترکیب حقایق استفاده کنید.</p>
</div>
    <label for="id_condition">
        شرط:
        <textarea rows="4" cols="50" name="condition" id="id_condition" readonly>{{ condition }}</textarea>
        <button type="button" id="NewBtn" name="NewBtn" class="button button1" onclick=
        "window.location.href ='{% url "ServiceUser:user_expert_createcondition"  exp_id%}'">انتخاب و ترکیب حقایق</button><br>
    </label>
    <label for="id_consequence">
        نتیجه:
        <select class="js-example-basic-single" name="consequence" id="id_consequence"  required >
            {% for cons in consequence %}
            <option value="{{ cons.id }}">{{ cons }}</option>
            {% endfor %}
        </select>
        <input type="button" class="button button1" value="افزودن حقیقت جدید" onclick="addfactforeditrule()"><br>
    </label>

    <label for="id_ownerexpert">
        سیستم خبره قانون:
        <select class="js-example-basic-single" name="ownerexpert" id="id_ownerexpert"  required onchange="setdomains()">
            {% for exp in ownerexpert %}
            <option value="{{ exp.id }}">{{ exp|truncatechars:100 }}</option>
            {% endfor %}
        </select>
    </label>
    <label for="id_domain">
        حوزه دانش قانون:
        <select class="js-example-basic-single" name="domain" id="id_domain"  required onchange=" setfacts()">
            {% for dom in domain %}
            <option value="{{ dom.id }}">{{ dom|truncatechars:100 }}</option>
            {% endfor %}
        </select>
        <input type="button" class="button button1" value="افزودن حوزه دانش جدید" onclick="adddomainforeditrule()"><br>
    </label>
    <label for="id_pub_date">
        تاریخ ایجاد:
        <!--<input type="text" name="pub_date" class='persiandp' id="id_pub_date" value="{{ form.pub_date.value }}">-->
        {{form.pub_date}}
    </label>
<hr>
<p>
    <input type="submit" class="button button1" value="ذخیره تغییرات" />
</p>
<script>
function addtext() {
    var itemselected = parseInt(document.getElementById("id_factlist").value);
    var itemtext = document.getElementById("id_factlist").children[itemselected].innerHTML;
    var condtext = document.getElementById("id_condition").value;
    document.getElementById("id_condition").value = itemtext;
    document.getElementById("test").value = itemtext;
     }

function initform() {
        {#alert('in init');#}
        window.sessionStorage.setItem('redirectpage','');
        var domainval = document.getElementById('id_domain').value;
        window.sessionStorage.setItem('domain',domainval);
        let expval = document.getElementById('id_ownerexpert').value;
        window.sessionStorage.setItem('ownerexpert',expval);
        window.sessionStorage.setItem('responsepage',"");
        setdomains();
        setfacts();

}

function setfacts() {
  var csrftoken = '{{ csrf_token }}';
  var condstr = document.getElementById('id_condition').value;
  var currdomain = window.sessionStorage.getItem('domain') ;
  var domainval = document.getElementById('id_domain').value;
  window.sessionStorage.setItem('domain',domainval);
  var  xmlhttp, ResponseObj;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === 4 && this.status === 200) {
      ResponseObj = JSON.parse(this.responseText);
      var factlist = document.getElementById('id_consequence');
      if(currdomain !== domainval) {
          document.getElementById('id_condition').innerText = '';
      }
      factlist.innerText='';
      for (x in ResponseObj) {
          var opt =document.createElement('option');
          opt.text = ResponseObj[x].fact;
          opt.value = ResponseObj[x].id;
          factlist.options.add(opt);
      }
      }else{
          # show some help msg
    }
    };
  xmlhttp.open("POST", "{% url 'RuleManager:update_facts' %}", true);
  xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xmlhttp.setRequestHeader("X-CSRFToken", csrftoken);
  {#xmlhttp.send('domain='+domainval+'&fact='+condfact);#}
  xmlhttp.send('domain='+domainval+'&facteffect=consequence');
}

function setdomains() {
  var csrftoken = '{{ csrf_token }}';
  var currexpert = window.sessionStorage.getItem('ownerexpert') ;
  var expertval = document.getElementById('id_ownerexpert').value;
  window.sessionStorage.setItem('ownerexpert',expertval);
  var  xmlhttp, ResponseObj;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === 4 && this.status === 200) {
      ResponseObj = JSON.parse(this.responseText);
      var domlist = document.getElementById('id_domain');
      if(currexpert !== expertval) {
          document.getElementById('id_condition').innerText = '';
      }
      domlist.innerText='';
      for (x in ResponseObj) {
          var opt =document.createElement('option');
          opt.text = ResponseObj[x].desc
          opt.value = ResponseObj[x].id;
          domlist.options.add(opt);
      }
      let curdomain = document.getElementById('id_domain').value;
      window.sessionStorage.setItem('domain',curdomain)
      }else{
        # show some help msg
    }
    };
  xmlhttp.open("POST", "{% url 'RuleManager:update_domains' %}", true);
  xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xmlhttp.setRequestHeader("X-CSRFToken", csrftoken);
  {#xmlhttp.send('domain='+domainval+'&fact='+condfact);#}
  xmlhttp.send('ownerexpert='+expertval);
}

function extractafact(conds) {
    var tempres = [];
    if (conds===''){
        return ''
    }
    {#alert('in extractafact');#}
    var splited = conds.split(' AND ', 1);
    {#alert('spl:'+splited.toString()+'rrr:'+splited[0]);#}
    {#alert('gggggggggggg');#}
    if (!splited.includes(' AND ')) {
        {#alert('in extractafact not and');#}
        if (!splited[0].includes(' OR ')) {
            {#alert('in extractafact not or');#}
            tempres.push((splited[0]));
            {#alert('in extractafact tempres:'+tempres.toString());#}
        } else {
            {#alert('in extractafact not else or:'+splited[0]);#}
            splited = splited[0].split(' OR ', 1);
            tempres.push(splited[0]);
            tempres.push(extractfactdomain(splited[1]))
        }
    } else {
        {#alert('in extractafact and contains');#}
        tempres.push((splited[0]));
        {#alert('in extractafact'+tempres.toString());#}
        tempres.push(extractfactdomain(splited[1]))
    }
    {#alert('in extractafact ==========');#}
    if (!tempres[0].includes('NOT')) {
        {#alert('in extractafact tempres[0]:'+tempres[0]);#}
        return tempres[0];
    } else {
        splited = tempres[0].split('NOT',1);
        return splited[1];
    }
}

if(window.attachEvent) {
    window.attachEvent('onload', initform);
} else {
    if(window.onload) {
        var curronload = window.onload;
        var newonload = function(evt) {
            curronload(evt);
            initform(evt);
        };
        window.onload = newonload;
    } else {
        window.onload = initform;
    }
}
</script>

</form>
        </div>
    </div>
{% endblock %}