Contract_Assistant/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from ServiceUser.UserManagement import logoutuser, appuser, loginuser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', loginuser.verifyuser, name='signin'),
    path('signout/', logoutuser.finishconnection, name='sinout'),
    # path('register/', appuser.pricing, name='register'),
    path('register/', appuser.register2, name='register'),
    path('pricing/', appuser.pricing, name='princing'),
    path('RuleManager/', include('RuleManager.urls')),
    path('rulemanager/', include('RuleManager.urls')),
    path('ruleManager/', include('RuleManager.urls')),
    path('Rulemanager/', include('RuleManager.urls')),
    path('ServiceUser/', include('ServiceUser.urls')),
    # path('create-rule/', include('RuleManager.urls')),
    path('expertsystem/', include('ExpertSystem.urls')),
    path('Expertsystem/', include('ExpertSystem.urls')),
    path('', include('ExpertSystem.urls')),
    path('plans/', include('plans.urls')),
    path('zarinpal/', include('zarinpal.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/newpassword_reset_form.html',
        email_template_name = 'registration/newpassword_reset_email.html',
        subject_template_name= 'registration/newpassword_reset_subject.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/newpassword_reset_done.html')
         , name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/newpassword_reset_confirm.html')
         , name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/newpassword_reset_completed.html')
         , name='password_reset_complete'),
]

ExpertSystem/urls.py
from django.urls import  path
from . import forms, views
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ExpertSystem'
urlpatterns = [
    path('contractdemo', forms.initengine, name='expert_initial'),
    path('classiccontractdemo', forms.initengine_classic, name='expert_initial_classic'),
    path('update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    # path('', views.luncher, name = 'luncher'),
    # path('', login_required(PricingView.as_view(template_name='ExpertSystem/home.html')), name = 'luncher'),
    path('', PricingView.as_view(template_name='ExpertSystem/home.html'), name = 'luncher'),
    path("expert_contract/", forms.Creat_Expert, name='expert_contract'),
    path('ContractExpert/', forms.Creat_Expert, name='expert_contract'),
    path('expert_contract_byajax/', views.expert_contract_byajax, name='expert_contract_byajax'),
    path('rewindengine/', views.rewindengine, name='rewindengine'),
    path('update_facts/', views.update_facts, name='update_facts'),

    path('about/', views.about, name='about'),
    path('contact/', forms.contact, name='contact'),
    # path('RuleManager/', include('RuleManager.urls')),
]

ServiceUser/urls.py
from django.urls import path, include
from . import forms, views
from .UserManagement import loginuser, appuser
from RuleManager import views as Rule_views
from RuleManager import forms as Rule_forms
from .messagemanager import restore_default_messages
from plans.views import PricingView
from django.contrib.auth.decorators import login_required

app_name = 'ServiceUser'
urlpatterns = [
    # *** auth user urls ***
    path('create_user/', forms.create_user, name='create_user'),
    path('create_user/result', views.create_user_result, name='create_user-result'),
    path('edit_user/', appuser.edit_user, name='edit_user'),
    # *** auth user urls ***

    # *** supervisor urls ***
    path('supervisors/', views.supervisorlist, name='supervisorlist'),
    path('supervisors/create/', forms.create_supervisor, name='create_supervisor'),
    path('supervisors/<int:sup_id>/', views.supervisor_detail, name='supervisordetail'),
    path('supervisors/edit/<int:sup_id>/', forms.edit_supervisor_by_index, name='edit_supervisor'),
    path('supervisors/delete/<int:sup_id>/', views.delete_supervisor_by_index, name='delete_supervisor'),
    # *** supervisor urls ***

    # *** developer urls ***
    path('developers/', views.developerlist, name='developerlist'),
    path('developers/create/', forms.create_developer, name='create_developer'),
    path('developers/<int:dev_id>/', views.developer_detail, name='developerdetail'),
    path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** developer urls ***

    # *** appuser urls ***
    path('plans/', include('plans.urls')),
    # path('', views.dashboard2, name='user_dashboard'),
    path('', views.dashboard, name='user_dashboard2'),
    path('noaccess/', views.permission, name='Forbidden_content'),
    path('registration/<mode>/', appuser.register, name='registration'),
    # path('registration/', appuser.register2, name='registration'),
    path('registration/activate/<uidb64>/<token>/', appuser.activate, name='activate'),
    # path('account/', views.account, name='user_account'),
    path('account/',login_required(PricingView.as_view(template_name='ServiceUser/useraccount2.html')) , name='user_account2'),
    path('account/upgrade/', forms.upgradeaccount, name='upgrade_user_account'),
    path('account/limitations/', views.accountlimit, name='accountlimit'),
    path('payments/', views.paymentlist, name='user_payments'),
    path('staffs/', views.userstaffs, name='user_staffs'),
    path('staffs/add/', forms.create_employee, name='create_userstaff'),
    path('staffs/<int:staff_id>/edit/',forms.edit_employee_by_index, name='edit_userstaff'),
    path('staffs/<int:staff_id>/delete/', views.delete_employee_by_index, name='delete_userstaff'),
    path('staffs/<int:staff_id>/detail/', views.staffdetail, name='user_staffdetail'),
    path('experts/', views.userexperts, name='user_expertmodel'),
    path('experts/config', forms.configengine, name='engineconfig'),
    path('experts/config/restore', restore_default_messages, name='restoredefaults'),
    path('experts/add/', forms.create_expertmodel, name='create_expertmodel'),
    path('experts/<int:exp_id>/', views.userexpertdetail, name='user_expertdetail'),
    path('experts/<int:exp_id>/controlpanel/', views.controlpanel, name='controlpanel'),
    path('experts/<int:exp_id>/update_facts/', views.update_domain_facts, name='update_facts'),
    path('experts/<int:exp_id>/edit/', forms.userexpertedit, name='user_expert_edit'),
    path('experts/<int:exp_id>/delete/', views.userexpertdelete, name='user_expert_delete'),
    path('experts/<int:exp_id>/start/', forms.userexpertstart, name='user_expert_start'),
    path('experts/<int:exp_id>/start/update_detailfacts/', forms.update_detailfacts, name='update_detailfacts'),
    path('experts/<int:exp_id>/startclassic/', forms.userexpertstartclassic, name='user_expert_start_classic'),
    path('experts/<int:exp_id>/startclassic/update_detailfacts/', forms.update_detailfacts, name='update_classic_detailfacts'),
    path('experts/<int:exp_id>/RuleManager/', Rule_views.index, name='user_expertrules'),
    path('experts/<int:exp_id>/RuleManager/create_condition', Rule_forms.create_condition,
         name='user_expert_createcondition'),
    path('experts/<int:exp_id>/RuleManager/controlpanel', Rule_views.controlpanel,
         name='user_expert_controlpanel'),
    path('experts/<int:exp_id>/RuleManager/add/',Rule_forms.create_rule_by_model ,
         name='user_expertnewrule'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/',Rule_views.detail ,
         name='user_expertrule_detail'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/edit/',Rule_forms.edit_rule_by_index,
         name='user_expertrule_edit'),
    path('experts/<int:exp_id>/RuleManager/<int:rule_id>/delete/',Rule_views.delete_rule_by_index,
         name='user_expertrule_delete'),
    path('experts/<int:exp_id>/RuleManager/facts',Rule_views.factlist , name='user_expertfacts'),
    path('experts/<int:exp_id>/RuleManager/facts/add',Rule_forms.create_fact_by_model ,
         name='user_expertnewfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload',Rule_forms.upload_fact_file ,
         name='user_expert_uploadfact'),
    path('experts/<int:exp_id>/RuleManager/facts/upload/result',Rule_views.upload_fact_result ,
         name='factupload_result'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/',Rule_views.factdetail ,
         name='user_expertfact_detail'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/edit/',Rule_forms.edit_fact_by_index ,
         name='user_expertfact_edit'),
    path('experts/<int:exp_id>/RuleManager/facts/<int:fact_id>/delete/',Rule_views.delete_fact_by_index ,
         name='user_expertfact_delete'),
    path('experts/<int:exp_id>/RuleManager/domains', Rule_views.domainlist, name='user_expertdomains'),
    path('<username>/experts/<int:exp_id>/RuleManager/domains/add', Rule_forms.create_domain_by_model,
         name='user_expertnewdomain'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/', Rule_views.domaindetail,
         name='user_expertdomain_detail'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/edit/', Rule_forms.edit_domain_by_index,
         name='user_expertdomain_edit'),
    path('experts/<int:exp_id>/RuleManager/domains/<int:dom_id>/delete/', Rule_views.delete_domain_by_index,
         name='user_expertdomain_delete'),
    path('experts/<int:exp_id>/RuleManager/domains/add',Rule_forms.create_domain_by_model ,
         name='user_expertnewdomain'),

    # path('<username>/experts/create', views.developer_detail, name='developerdetail'),
    # path('developers/edit/<int:dev_id>/', forms.edit_developers_by_index, name='edit_developer'),
    # path('developers/delete/<int:dev_id>/', views.delete_developer_by_index, name='delete_developer'),
    # *** appuser urls ***

]

zarinpal/urls.py
# Github.com/Rasooll
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('', views.verify , name='verify'),
]

ExpertSystem/models.py
from django.db import models
from ServiceUser.models import App_User, Employee
# from RuleManager.models import Rules, Facts
# Create your models here.
class Comments(models.Model):

    name = models.CharField( max_length=255, blank=False )
    email=models.EmailField(max_length=255, blank=False )
    subject = models.TextField(max_length=3000, blank=False )

    def __str__(self):
        return (self.subject[:100] + '...') if len(self.subject) > 100 else self.subject

class Expertmodel(models.Model):
    _PUB = 'PUBLIC'
    _USER = 'RESTRICTED'
    _ACCESS = [(_PUB, 'دسترسی عمومی'),(_USER, 'دسترسی فقط برای کاربران')]
    name = models.CharField(max_length=200, verbose_name='نام سیستم خبره')
    appuser = models.ForeignKey('ServiceUser.App_User', on_delete=models.DO_NOTHING, related_name='user', verbose_name='مالک سیستم خبره')
    accesstype = models.CharField(choices=_ACCESS, default=_PUB,max_length=10,  verbose_name='نحوه دسترسی به سیستم خبره')
    # authorizedusers = models.ManyToManyField(Employee,related_name='allowedusers_fiels',
    #                                          limit_choices_to=Employee.objects.filter(manager=appuser))



    def get_related_facts(self):
        fact_set =self.factowner_field.all()
        if fact_set.count():
            return fact_set
        else:
            return None

    def get_related_rules(self):
        rule_set =self.ruleowner_field.all()
        if rule_set.count():
            return rule_set
        else:
            return None

    def get_related_domains(self):
        domain_set = self.domainowner_field.all()
        if domain_set.count():
            return domain_set
        else:
            return None

    def __str__(self):
        return self.name

    def getowneruser(self):
        return self.appuser.user_auth.username

ExpertSystem/templates/ExpertSystem/expert_contract.html
{% extends "expertbase.html" %}
<!--{% load static %}-->

<!--<link rel="stylesheet" type="text/css" href="{% static '/ExpertSystem/css/style.css' %}">-->
{% block title_html %}
سیستم خبره قراردادها
{% endblock %}
{% block h1 %}
متخصص قرارداد
{% endblock %}
{% block article_content %}
<form id="expertform" method="post" action="{% url "ExpertSystem:expert_contract" %}" >
{% csrf_token %}

<h2>پیام سیستم:</h2>
<br>
<br>

<h3>{{ question }}</h3>
<br>
<br>

    {% if  question_type == 'Y/N'%}
        <select name="ynselect">
             <option value="بلی">بلی</option>
             <option value="خیر">خیر</option>

        </select>
        <br>

    {% elif question_type == "EXP" %}

        <h3>پاسخ شما:</h3>
        <input name="answer" type="number">
        <br>
    {% else %}
        <script type="text/javascript" >
            {#alert('sfddsfg');#}
            document.getElementById('prevBtn').textContent = 'dsdsdasdd';
            {#document.getElementsByName("prevBtn").disabled = true;#}
            {#alert('12165165');#}
        </script>
        <h2 >
             اتمام عملیات
             <h3>
              مهندس دانش : رحمان زارعی <br>
              طراح سیستم: رحمان زارعی

             </h3>
        </h2>
    {% endif %}
<br>

<br>
    <button type="button" id="prevBtn" name="prevBtn" disabled>مرحله قبل</button>
<div>
    <button type="submit" id="nextBtn" name="nextBtn">مرحله بعد</button>
</div>

<br>
<button  type="button"  onclick="window.location.href = '{% url "ExpertSystem:expert_initial" %}'">رفتن به صفحه تنظیمات اولیه</button>
{#<input type="text" value="رفتن به صفحه تنظیمات اولیه" onclick="gotosettings()">#}
<br>
<br>
<input  type="button" value="به من بگو چرا" onclick="showmewhy()">
<br>
<br>
<input  type="button" value="به من بگو چگونه" onclick="showmehow()">
<br>
<h4 id="whythis" >چرا:</h4>
<br>
<h4 id="howthis" >چگونه:</h4>

<script>
function gotosettings()
{
    alert('gd888ggd');
    {#window.location.href = '{% url "ExpertSystem:expert_initial" %}';#}
}
function showmewhy() {
    document.getElementById('whythis').innerHTML='چرا: <br>'+ '{{ whythisquestion }}';
}
function showmehow() {
    document.getElementById('howthis').innerHTML='چگونه: <br>'+'{{ howthisanswer }}';
}

</script>

</form>

{% endblock %}

ExpertSystem/templates/ExpertSystem/google40e0640a26657690.html
google-site-verification: google40e0640a26657690.html

ExpertSystem/templates/ExpertSystem/user_expertengine.html
<!DOCTYPE html>
<html lang="fa">
<head>
<meta name="description" content="دستیار هوشمند ">
<meta name="keywords" content="سیستم خبره,نرخ حق بیمه تامین اجتماعی,هوش مصنوعی,تعیین حق بیمه,مدیریت قوانین,ExpertSystem, Artificial Intelligence">
<meta name="author" content="رحمان زارعی">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>سامانه هوشمند</title>
{% load static %}
<link href="{% static "/ExpertSystem/css/expertstyle.css" %}" rel="stylesheet" type="text/css"/>
<link href="{% static "/ExpertSystem/css/menustyle.css" %}" rel="stylesheet" type="text/css" />
<link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static '/admin/js/django_jalali.min.js' %}"></script>
<link rel="stylesheet" href="{% static '/admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<script src="{% static 'ServiceUser/javascript/menuscripts.js' %}" defer></script>
    <script >
        var jQuery_3_4_1 = $.noConflict(true);
        user = '{{user.username}}';
        $(document).ready(function(){
            manageuser(user);
            $('.persiandp').datepicker({
	            changeMonth: true,
	            changeYear: true,
                numberOfMonths: 1,
	            {#showButtonPanel: true,#}
                {#showWeek: true,#}
	            dateFormat: 'dd/mm/yy',
                {#dateFormat: 'yy/mm/dd',#}
	            {#autoSize: true,#}
                {#showOn: 'button',#}
	            {#buttonImage: '/static/admin/img/icon-calendar.svg',#}
	            {#buttonImageOnly: true#}
	        });
	        $('#id_signin').click(function(){
                let log_state = '{{ user.is_authenticated}}';
                if (log_state == 'True'){
                    $('#id_userpanel').show();
                    $('#editbtn').click(function(){
                     window.location.href ='{% url 'ServiceUser:edit_user'  %}';
                    });
                    $('#logoffbtn').click(function(){
                        window.location.href ='{% url 'sinout'  %}';
                    });
                }
                else {
                    window.location.href ='{% url 'signin'  %}';
                }
            });
	         $ = jQuery_3_4_1;
            $('.js-example-basic-single').select2({
                dir: "rtl"
            });
            $('.js-example-basic-multiple').select2({
                dir: "rtl"
            });

        });
    </script>
<style>
    body {
    font-family: "B Yekan",Tahoma, sans-serif;
}
</style>
</head>
<body >
    {% include 'ServiceUser/topnavmenu.html' %}
<div class="contentcontainer" >
        {% include "ServiceUser/userpanel.html" %}
        {% include "ServiceUser/UserManagement/custom_expiration_msg.html" %}


<h1 >راه اندازی سامانه هوشمند</h1>
<div class="contentcontainer">
<div class="row">
    <div class="contentcolumn">
        <div class="infomsg">
        <div class="infoheader">اطلاع</div>
        <p >
            سامانه هوشمند تعیین نرخ حق بیمه با استفاده از روش های هوش مصنوعی به شما در تشخیص نرخ حق بیمه قراردادهای پیمانکاری کمک می کند.
            کافی است اطلاعات اولیه ای که ازقرارداد دارید را از جدول زیر انتخاب کنید و دکمه شروع را بزنید.
            با پاسخ دادن به چند سوال نرخ حق بیمه قرارداد برای شما نمایش داده می شود
        </p>
        <br>
        راهنمایی سریع:
        <ol class="numbered ">
            <li>
                <p> از لیست موجود در ردیف اول(نحوه شروع به کار موتور استنتاج)، انتخاب اطلاعات از پایگاه حقایق را انتخاب کنید. این گزینه برای زمانی به کار برده می شود که شما دانشی در زمینه موضوع کار دارید.
                در این حالت با انتخاب اطلاعات سامانه هوشمند بر اساس این اطلاعات و بر اساس دانش قبلی سوالاتی از کاربر می پرسد و در طی مراحلی چنانچه دانشی در این رابطه وجود داشته باشد کاربر را به جواب نهایی راهنمایی می کند.
                </p>
            </li>
            <li>
                از لیست موجود در ردیف اول(نحوه شروع به کار موتور استنتاج) ، انتخاب بصورت تصادفی را انتخاب کنید و دکمه شروع را کلیک کنید.
            </li>
            <li>
                از لیست موجود در ردیف اول(نحوه شروع به کار موتور استنتاج)، از اولین قانون پایگاه داده را انتخاب کنید و دکمه شروع را کلیک کنید.
            </li>
        </ol>
    </div>
        <div class="alerttext">
            <div class="alertheader">توجه</div>
                <p>
                    نکته:گزینه های دوم و سوم جهت آزمایش کارایی سیستم در حالت عمومی یا کسب اطلاعات در مورد دانش زمینه کار می باشد.
                </p>
        </div>
        <form id="expertinitial" method="post"  action="{% url "ServiceUser:user_expert_start" exp_id%}  ">
            <label for="inittype">نحوه شروع به کار موتور استنتاج</label>
            <select id="inittype" class="js-example-basic-single" name="inittype"  oninput="inittypeselect()" required >
              <option value="priorfact" selected>انتخاب اطلاعات از پایگاه حقایق اولیه</option>
              <!--<option value="first" >از اولین قانون پایگاه داده</option>-->
              <!--<option value="random"> انتخاب بصورت تصادفی</option>-->
            </select>
            <label for="factlist">اطلاعات اولیه </label>
            <!--<select id="factlist" name="factlist"  multiple size="10">-->
            <select class="js-example-basic-multiple" id="factlist" name="factlist[]" multiple="multiple">
                {% for f in facts %}
                    <option value="{{ f.fact}}"> {{f.fact}}</option>
                {% endfor %}

            </select>
            <label for="datalist">حوزه دانش </label>
            <!--<select id="datalist" name="datalist" required  onchange="change_db()" >-->
            <select class="js-example-basic-single" name="datalist" id="datalist"  required onchange="change_db()">
                {% for data in databases %}
                    <option value={{ data.id}}> {{ data}}</option>
                {% endfor %}
            </select>
            <hr>
            <button type="submit" id="nextBtn" class="button button1">شروع </button>
            {% csrf_token %}
        </form>
    </div>
</div>
</div>

<script>
function inittypeselect() {
    var inittype = document.getElementById('inittype').value;
    var factlist = document.getElementById('factlist');
    {#alert(inittype);#}
    if (inittype==='priorfact') {
        factlist.disabled=false;
    }
    else {
        factlist.disabled=true;
    }

  }

function allvalues() {
      var factlist = document.getElementById('factlist');
      var opts = [], opt;

    // loop through options in select list
      for (var i=0, len=factlist.options.length; i<len; i++) {
          opt = factlist.options[i];

        // check if selected
          if ( opt.selected ) {
            // add to array of option elements to return from this function
              opts.push(opt);
        }
    }
  }

function change_db() {
  var db_id = document.getElementById('datalist').value;
  var  xmlhttp, ResponseObj;
  xmlhttp = new XMLHttpRequest();
  xmlhttp.onreadystatechange = function() {
    if (this.readyState === 4 && this.status === 200) {
      ResponseObj = JSON.parse(this.responseText);
      {#alert('my parsed resp is:---'+ResponseObj);#}
      var factlist = document.getElementById('factlist');
      factlist.innerText='';
      for (x in ResponseObj) {
          var opt =document.createElement('option');
          opt.text = ResponseObj[x].fact;
          opt.value = ResponseObj[x].id;
          factlist.options.add(opt);
      }
      }
    };
  xmlhttp.open("POST", "{% url 'ServiceUser:update_facts' user exp_id%}", true);
  xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  xmlhttp.send('db_id='+db_id);
}

function setactive(event)
{
    var x = event.target;
    x.classList.toggle("active");
}

function responsemenu() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}

function manageuser(user)
{
    if(user!=='not_signed_in')
    {
        document.getElementById('id_signin').innerText = user;
        document.getElementById('id_signin').style.textShadow = "2px 2px 4px #000000";
        document.getElementById('id_signin').style.borderBottomStyle = "outset  ";
        document.getElementById('id_signin').style.borderColor='black';
        document.getElementById('id_signin').style.borderBottomWidth="medium";
        document.getElementById('id_register').remove();
    }else
    {
        // alert('not_signed_in');
        document.getElementById('id_signin').innerText = 'ورود';
        var navlinks = document.getElementById('myTopnav');
        var len = navlinks.children.length;
        if(navlinks.children[len-1].innerText!=='ثبت نام')
        {
            var reglink = document.createElement("a");               // Create a <a> element
            reglink.innerText = "ثبت نام";
            reglink.href= '{% url "princing"%}';
            reglink.className = "left";
            reglink.id = 'id_register';
            navlinks.splice(len-1, 0, reglink);
        }
    }
}
</script>

</body>
<div class="footer">
    <h4>تمام حقوق محفوظ است
        <i class="fa fa-copyright"></i>
        1399
    </h4>
</div>

</html>